n1=int(input('digite um número:'))
n2=int(input('digite outro número:'))
soma=(n1+n2)
subtração=(n1-n2)
multiplicação=(n1*n2)
divisão=(n1/n2)
print(f'a soma desses núemeros é {soma}')
print(f'a subtração desses núemeros é {subtração}')
print(f'a multiplicação desses núemeros é {multiplicação}')
print(f'a divisão desses núemeros é {divisão}')